# Generated by Django 3.2.6 on 2021-08-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bs_option',
            name='dividend_yield',
            field=models.FloatField(default=0, verbose_name='Dividend Yield'),
        ),
        migrations.AddField(
            model_name='bs_option',
            name='style',
            field=models.CharField(default='Call', max_length=200, verbose_name='Call or Put'),
        ),
    ]
